### ISSUE TITLE
In system7.app at least, turn off Virtual Memory

### ISSUE THREAD

**Issue by BiggerJ** [mihaip/infinite-mac#114]
Virtual Memory makes some programs not work correctly, and the Memory control panel says there isn't enough hard drive space for it to work anyway (which would explain why it hasn't caused any problems with programs whose readmes say to turn off the feature). If you ever increase hard drive space, then please set it to be off by default, it'll start making some programs stop working as they should,

**Comment by mihaip** [comment]
Sounds reasonable, I don't recall intentionally turning on virtual memory.

**Comment by that-ben** [comment]
> Sounds reasonable, I don't recall intentionally turning on virtual memory.

Please note that in most PowerPC builds of classic Mac OS (namely Mac OS 8 and 9) virtual memory comes enabled by default, due to computers in the 90's shipping with an absurdly low amount of RAM.  e.g. my original bondi blue iMac G3 (233mhz) came from factory with only 32MB of RAM.  Due to the fact that all emulators nowadays can EASILY be dedicated 1GB of RAM, there is no point in enabling virtual memory in any of them, plus they cause major lag issues, sound/music stuttering, unplayable games, etc... virtual memory (hard disk swapping) is a horrible concept that I'm glad does not exist anymore.
