### ISSUE TITLE
Complex Mac to Infinite Mac copies

### ISSUE THREAD

**Issue by LeighGus** [mihaip/infinite-mac#175]
Please implement an ability to copy folders, nested folders, and large numbers of files. I define large as up to 10,000.

Thank you,

LeighGus@Mac.com

**Comment by that-ben** [comment]
Just wrap your thousands of items in a disk image and then drag and the disk image to Infinite Mac.  Problem solved.

**Comment by LeighGus** [comment]
Disk Utility does not create a disk image usable in Mac OS 9. How would I create a usable image? There is no option to create a .iso image.

**Comment by that-ben** [comment]
Sorry, but .iso I was intrinsically referring to .cdr which macOS produces instead of ISO, but the result will be compatible with Mac OS 8.1 and up (including Mac OS 9.0.4 that SheepShaver emulates).

I'm a command line person, so here's an article I wrote 5 years ago which gives a simple Terminal command that you can run on your folder full of subfolders/files.  It will take a HFS+ CDR image (almost the same as ISO and compatible with Mac OS 8.1 and up).  This was under Mac OS X, but I'm sure it still works in 10.13.  The trick is to use HFS+ as the volume format.  https://www.macintoshrepository.org/articles/122-how-to-create-a-hfs-disk-image-in-mac-os-x-to-encapsulate-transfer-mac-os-9-and-earlier-files

If you're not a command line or Terminal person, know that you can achieve the same in the Disk Utility app but without knowing the exact macOS version that you're using, it's hard to provide exact instructions, although I'm sure if you look closely and go slow you'll find the appropriate options to achieve the same thing as the command.  The trick is to select HFS+ as the format and then to select CDR/MASTER DVD (or something along those lines) as the output file format.

**Comment by that-ben** [comment]
I went the extra mile and also made a UI tutorial for you... Hope you like it :)

STEP 1: Put all your files and subfolders all together in 1 folder.  Then launch Disk Utility and pull the menus to make a disk image from a folder:
![step1](https://user-images.githubusercontent.com/13210399/233694820-ea3c0399-85ad-4254-bfb2-76b7a5db99e2.png)

STEP 2: Save it with the hybrid HFS+/ISO/UDF image format:
![step2](https://user-images.githubusercontent.com/13210399/233694987-8d77b209-870e-4eef-8d29-ca1aa29adab1.PNG)

STEP 3: Open the folder containing all your files in the Finder and you'll find the created disk image.  Now just append .iso to the end of the name.  This is required for InfiniteMac.org otherwise it will reject it:
![step3](https://user-images.githubusercontent.com/13210399/233695144-8026d06b-437b-4d78-a84f-8464241aacc7.PNG)

STEP 4: Enjoy.  Visit MR and join us in the chat for more old Mac tricks at https://www.macintoshrepository.org/chat_v2.php

**Comment by mihaip** [comment]
A disk image is one way to do this, and I'm planning on allowing entire folders to be dragged over too (as part of #164).
