### ISSUE TITLE
Possible native apps?

### ISSUE THREAD

**Issue by LeighGus** [mihaip/infinite-mac#176]
Would it be possible to create local app versions of these VM?

LeighGus@Mac.com

**Comment by that-ben** [comment]
Imagine opening Xojo, slapping a HTML canvas on an empty window, setting the home URL to InfiniteMac.org and compiling it to an .exe hahahah XD Problem solved ;-)

**Comment by LeighGus** [comment]
Actually I am hoping for a local version that would run on a Mac, specifically a high end M1 based MacBook Pro. But my Win 11 VM runs really well (Parallels) so a .exe would work as well. I'm hoping to escape the need for web based resources.

**Comment by that-ben** [comment]
If you want to run this OFFLINE then:
SheepShaver native build for macOS: https://www.emaculation.com/forum/viewtopic.php?f=20&t=7360
BasiliskII native build for macOS: https://www.emaculation.com/forum/viewtopic.php?f=6&t=7361

**Comment by mihaip** [comment]
@that-ben is right that if you're looking to run things locally, using the native builds of [SheepShaver](https://www.emaculation.com/doku.php/sheepshaver), [Basilisk II](https://www.emaculation.com/doku.php/basilisk_ii) II or [Mini vMac](https://www.emaculation.com/doku.php/mini_vmac) (depending on which OS version you're interested to run) are the way to go.

Infinite Mac is explicitly about running on the web, so that no installation is required.

**Comment by parkerlreed** [comment]
Another fun option is using the nativefier options to conform directly to the monitor size and disable borders

![image](https://user-images.githubusercontent.com/841440/234985851-3c31864a-273e-45f4-96b1-b6c9b6be1ad9.png)
