### ISSUE TITLE
Speed restrictions on BasiliskII based emulation? 

### ISSUE THREAD

**Issue by RonsCompVids** [mihaip/infinite-mac#239]
When you run BasiliskII outside of InfiniteMac, it runs as fast of the host machine will allow it to operate... which is especially helpful when doing large file copies or other operations that move at a snails pace on a real Mac.

So why are the BasiliskII based InfiniteMac VMs all seemingly locked to general approximation of the speed of a real Mac?

Would it be possible to remove this artificial speed restriction via the "Customize" menu?

**Comment by that-ben** [comment]
Could be related to #198

**Comment by RonsCompVids** [comment]
It's just really odd that it's speed limited at all considering that the regular BasiliskII is not speed restricted in any way.

**Comment by mihaip** [comment]
There are no speed restrictions (#198 is asking for them because it's still too fast in some cases). Running things under WebAssembly has some overhead, and loading files from Infinite HD has to go over the Internet, so that can also be slow depending on your connection speed.

What specifically is slow?

**Comment by that-ben** [comment]
Oh OK, but that is more prone to be your internet connection and/or the server load, because when you copy files from Infinite Mac, it has to download the actual sectors to your browser before it can "copy" them elsewhere.  That's way, WAY slower than a native emulator, which directly reads and writes to your local hard drive at like 100MB/s.

**Comment by RonsCompVids** [comment]
Thank you, that-ben!
