### ISSUE TITLE
Detect and auto-enable COMMAND -> CONTROL key swap for Mac users?

### ISSUE THREAD

**Issue by that-ben** [mihaip/infinite-mac#248]
Hi! I just received my iMac M3 and I found out that there's an annoyance in IM (e.g. Mac OS 9, but will do that also under Mac OS 8 and 7) when you use IM under a Mac.  You see, under Windows, if I do ALT-W to close a window, it works as intended.  But under Mac, if I do COMMAND-W, it closes the browser tab entirely.  I know I can swap COMMAND for the CONTROL key with 2 mouse clicks, but I need to do that every time I launch the emulator.

Couldn't we simply detect the platform using Javascript and if under any kind of Mac, then automatically enable the COMMAND -> CONTROL key swap? I'm sure this would make a lot of Mac users happy! I don't see the point of leaving it disabled under Mac, as that key combo is completely unusable in a Mac web browser.

**Comment by mihaip** [comment]
Something to consider, though I'd probably need to have an intro banner about it, because it's an unusual default for Mac users.

FWIW, the control/command key swap is now actually persistent (fixed in https://github.com/mihaip/infinite-mac/commit/52204d3a9c482e62be6ab081480611ab8a3add4e#diff-1c4d2da4d74e6951b49b86fc8ea7676a0d4b248a2037f2cd1fc3cf8131c83609), so you should need to do this only once.

**Comment by that-ben** [comment]
Yes but as it sits right now, it's unusable under a Mac because CMD-W closes the whole web browser.

**Comment by drj11** [comment]
As a Mac user by default and someone who has been annoyed by this Cmd- behaviour, can i vote for absolutely do not make swapping the keys a default. But it's probably a good idea to make the preference more visible.

**Comment by drj11** [comment]
i don't. but i don't wanting them to be swapped by default.

**Comment by drj11** [comment]
I think it's because i like the principle that Cmd- should be Cmd-. Yes, some of the Cmd-% commands might be stolen by the browser and never sent to the emulator, but they are not all stolen (or maybe they are for you, it's probably highly browser dependent).

I think it's easier (it's easier for me, for example) to understand that "Cmd- works but some commands are stolen by the browser" than no Cmd- works and i have no idea what key to press.

On objection i have to your "it's unusable on a Mac without them being swapped" is that that's exactly how i use it. And i wrote a HyperCard stack today.

**Comment by drj11** [comment]
I just realised you can enable Sticky Keys in the emulated Mac (Control Panel > Easy Access in System 6) and then tap Cmd- followed by W (for example). It works. Haha.

I can't say i particularly recommend it, but it gives us options.

**Comment by that-ben** [comment]
Ahhhhh yes! As 2 separate key strokes, genius! 👍
