### ISSUE TITLE
Custom resolution on Infinite Mac?

### ISSUE THREAD

**Issue by Bonzey2416** [mihaip/infinite-mac#263]
Do we have any suggestions for custom resolutions on Infinite Mac, like 800x480, 1024x600, 1280x720, 1366x768, 1440x900, 1600x900, 1920x1080 and 1920x1440?

**Comment by Bonzey2416** [comment]
Yeah

**Comment by lg0735** [comment]
Don't see why not, could enter in a value for width and height in the custom Machine dialog.

Also could be useful to accurately simulate chosen Macs with their proper screen resolution from the factory, such as the Mac IIfx, which seems like it shipped with a 512x384 display, not whatever Infinite Mac displays (since it adapts the resolution to fill most of the screen)

**Comment by Bonzey2416** [comment]
Yeah!

**Comment by mihaip** [comment]
This is now implemented, you can pretend to have a Portrait Display: https://infinitemac.org/1991/System%207.0?screenSize=640x870

https://infinitemac.org/run has all the options:
<img width="460" alt="image" src="https://github.com/mihaip/infinite-mac/assets/513813/852151cd-703b-4552-8e63-81bbf8785d19">
