### ISSUE TITLE
Pre-release Mac OS?

### ISSUE THREAD

**Issue by ghost** [mihaip/infinite-mac#267]
I think it would be neat to have old pre-release versions of Mac OS in the CD-ROM library since we already have some Apple Developer CDs there. I would guess these would go into a new category, since these are definitely unstable. One potential problem is that there are a lot of these that were distributed in a format that is not a disk image.

**Comment by that-ben** [comment]
> there are a lot of these that were distributed in a format that is not a disk image.

Well, from what I see, .img were shoved in .sit archives starting circa 1995, when DiskCopy 6 was out.  The reason for .img.sit files emerging is that users continued to produce disk images using DiskCopy 6 but as opposed to DiskCopy 4 and earlier, DiskCopy 6.0 and later do not produce binary safe disk images.  Apple began shoving a resource fork in the .img file, so in order to preserve both forks, before moving it outside of a HFS/HFS+ partition, one has to encode it, thus .sit was used.  We would have to convert DiskCopy 6 .img images to DiskDup+ .dsk or .iso in order for them to be easily usable on any web platform.

**Comment by Lucas-mother3** [comment]
I think that if beta versions are decidedly included, I might ask for support for the Twiggy disk betas of Macintosh System 0.97/1.0. Mini vMac already has support for the Twiggy Mac 128K proto (2 revisions of the hardware in fact), so this should be easy. I also delved into getting the 4.3T revision ROMs for the Twiggy model because for some reason, it rejects the 4.3T ROM found online unless if the checksum list is modified or if checking ROM checksum is disabled.

As for other betas, I highly doubt about running Copland right now (with **no** known emulator capable of running it due to very limited hardware requirements), as well as buggy System Software (if you consider them as beta) because, aside from being buggy, it would also spell legal disaster.

**Comment by mihaip** [comment]
Merging into #143
