### ISSUE TITLE
Download via upload folder generate an incomplete zip

### ISSUE THREAD

**Issue by valguenichon** [mihaip/infinite-mac#272]
That's it.
I tried with Chrome and FF and the zip is created too soon (try with large files) while the copy in the upload folder is not over.

I'd like to add that it is a fantastic work you've done.

**Comment by mihaip** [comment]
This is rather difficult to fix -- there isn't a notification of when things are added to "Uploads" -- the best I can do is to periodically check if new items appear. However, since the parent folder gets created first, it's not immediately apparent that items are still being added to it.

What I usually do is to copy the folder to the top level of The Outside World, and once it's done, move it to "Uploads."

**Comment by valguenichon** [comment]
Nice workaround. Thanks a lot!
