### ISSUE TITLE
Store disk chunks in Cloudflare R2

### ISSUE THREAD

**Issue by mihaip** [mihaip/infinite-mac#288]
They're currently in Cloudflare Workers KV (because they're treated as files that `wrangler deploy` uploads). However, it's going to get expensive as the disk size grows (currently at ~3.3 GB, may be get significantly larger as more NeXTStep images are added for #121). 

[Workers KV pricing](https://developers.cloudflare.com/workers/platform/pricing/#workers-kv):
-  Storage: the first 1GB is free and then it's .50/GB-month
-  Reads: the first 10 million per month are free, and then it's $0.50/million. 

[R2 pricing](https://developers.cloudflare.com/r2/pricing/):
- Storage: 10 GB free and then 0.015/GB-month.
- Reads (Class B operations): the first 10 million per month are free, and then it's 0.36 / million.

So I would be within the free tier for quite a while.

**Comment by that-ben** [comment]
Isn't 10 million reads kind of low though? I guess it depends on how quick IM popularity rises, but I feel like 10M reads per month can easily be surpassed.

**Comment by mihaip** [comment]
This appears to have resulted in a nice drop in CPU time (not that we were anywhere near the limits):
![Screenshot 2024-03-24 at 11 49 32@2x](https://github.com/mihaip/infinite-mac/assets/513813/0d5dac96-cf52-4959-8f39-06e29375d27c)

And maybe a slight increase in wall time, but the correlation is not as clear
![Screenshot 2024-03-24 at 11 50 54@2x](https://github.com/mihaip/infinite-mac/assets/513813/1756b0f9-8232-40e2-bea3-a6656782521e)

**Comment by mihaip** [comment]
As far as cost, with March 3/4 done it's nowhere near the free read quota (class B operations), but it is approaching the end of the free storage tier:

![Screenshot 2024-03-24 at 11 55 10@2x](https://github.com/mihaip/infinite-mac/assets/513813/a01f19d6-40d7-4ad9-a641-d07a172e46ab)

**Comment by that-ben** [comment]
Well that's pretty good news.  March is a good month of the year to check stats, since it's quite a busy month of the year for retro Macintosh consumption.  If your quota was not close to being exceeded this month, it's a good sign you'll do fine for the rest of the year.  We usually see a ramp-up in March and April every year.

<img width="667" alt="Screenshot 2024-03-24 at 3 04 24 PM" src="https://github.com/mihaip/infinite-mac/assets/13210399/fb669b7e-7ea4-4888-a92d-2d2b8b4234e3">
