### ISSUE TITLE
Investigate Apple IIjse for Apple II Desktop/MouseDesk

### ISSUE THREAD

**Issue by upintheairsheep** [mihaip/infinite-mac#289]
Apple IIjse is an Apple IIe emulator in JS that supports mouse support natively, allowing to boot the obscure Apple II Desktop, also called Mouse Desk, which was Apple’s official desktop environment for the Apple IIe (which is a stripped down/beta version of GS/OS until the it was officially released). Note that the Apple II Desktop 1.3 and 1.2 are unofficial continuations of the software and not official. Apple II Desktop was originally called MouseDesk until 1986 until Apple purchased the software from the French company Version Soft, which previously made it.
https://github.com/whscullin/apple2js

**Comment by mihaip** [comment]
Thanks for suggesting this, but it's not something that I am interested in..

**Comment by inexorabletash** [comment]
Hey there! I'm the unofficial Apple II DeskTop/MouseDesk maintainer; this issue came across my search so I thought I'd pop in. Agreed it's not in scope for Infinite Mac. But in case anyone else comes across this issue... 

If users want to run A2D in the browser, as noted by @upintheairsheep there are existing web-based, zero-friction Apple II emulators like Apple //jse. And several can take a disk image URL as a parameter, and so can launch A2D with a single click. There are "try it in your browser" links off the [documentation](a2desktop.com) site or [release pages](https://github.com/a2stuff/a2d/releases/tag/v1.4-alpha7): 
* [Apple //jse](https://www.scullinsteel.com/apple//e?accelerator_toggle=true&gl_canvas=false&mono_screen=false#https://a2desktop.s3.amazonaws.com/A2DeskTop-1.4-alpha7-en_800k.2mg)
* [Apple2TS](https://apple2ts.com/?color=white&speed=fast#https://a2desktop.s3.amazonaws.com/A2DeskTop-1.4-alpha7-en_800k.2mg) 

(I'm a huge fan of Infinite Mac and frequently use it to research old versions of the Macintosh for inspiration. Given that Apple authored the GUI toolkit used by MouseDesk/A2D in 1985 and published "Human Interface Guidelines: The Apple Desktop Interface - For any Macintosh or Apple II computer" as late as 1987, it's fascinating to explore their early GUI experiments.)
