### ISSUE TITLE
I keep getting error 500 status when installing anything

### ISSUE THREAD

**Issue by naruse** [mihaip/infinite-mac#345]
Pretty much I am trying to install system 7.5.3 fromt the apple legacy recovery CD Rom and I keep getting this issue; is there any way to avoid this?, seems to be failing intermitently and I keep getting this error:

<img width="1221" alt="Screenshot 2024-10-08 at 8 39 32 PM" src="https://github.com/user-attachments/assets/9e2eeb0e-63af-4790-8be6-e5b0eb30564d">

When going through img12

Any thoughts on what could it be? -- this project is quite quite useful for me for creating installations on my bluescsi drive!

**Comment by that-ben** [comment]
It would be best to download the disk image to your computer, then to physically drag that file onto the InfiniteMac canvas to mount it.  Steaming disk images has never worked for me either, been trying in various IM releases for more than 1 year and it always quickly ends up with error 500.  Tried streaming from both ARCHIVE.ORG and Macintosh Repository with always the same result... but downloading the disk image and then dragging it onto IM always works for me.

**Comment by naruse** [comment]
Thanks @that-ben ! I will try that out! :)

**Comment by mihaip** [comment]
@naruse also note that https://archive.org/ is [still down](https://blog.archive.org/2024/10/18/internet-archive-services-update-2024-10-17/) due to a DDoS attack, so things will be even flakier than usual.

The under-development Library feature (#337) may also be a worthwhile alternative, see https://hachyderm.io/@mihaip/113222167182502747 for how to try it out.
