### ISSUE TITLE
Capture close window and quit application shortcuts?

### ISSUE THREAD

**Issue by VirtualWolf** [mihaip/infinite-mac#36]
I grew up with System 7 and Mac OS 8 and absolutely love this! I was playing around with it just now and reflexively hit Cmd-W to close the window inside Infinite Mac and instead closed my whole browser tab instead. 😂 Would it be worth (and in fact even possible?) to have those keyboard shortcuts work within Infinite Mac instead?

**Comment by mihaip** [comment]
Unfortunately the browser does not normally allow those shortcuts to be handled by pages, otherwise malicious sites could try to prevent you from closing tabs.

When you take the emulator full-screen (by clicking on the apple logo on the monitor), then I'm able to use the [keyboard lock API](https://web.dev/keyboard-lock/) to handle all key events, in which case Command-W (and Command-Q) should work as expected.

I've also filed #10 as an alternative (since control is normally not used in classic Mac OS), but it would require having a configuration/preferences UI, which I haven't gotten around to building yet.

**Comment by VirtualWolf** [comment]
Ahh, nice! I didn't even realise there was a full screen mode, that'll do the trick. Cheers!
