### ISSUE TITLE
Feature request: Set file type / creator for known file formats dragged into the window

### ISSUE THREAD

**Issue by asvitkine** [mihaip/infinite-mac#52]
Feature request: Set file type / creator for known file formats dragged into the window.

Ideally, if you drag, say a .sit file, it will be appropriately associated with Stuffit Expander in the emulator so that it can just be double clicked.

I think this could be done by having the emulator have a hardcoded mapping for some common file format extensions and set the type/creator codes appropriately.

**Comment by mihaip** [comment]
This already happens, it's something that BasiliskII does on the ExtFS filesystem, here's the mapping: https://github.com/mihaip/macemu/blob/ff88805eb9a72b22e5346039108e50ec62c5d7cf/BasiliskII/src/Unix/extfs_unix.cpp#L161-L220

It seems to be working too, if you inspect the metadata using ResEdit:
<img width="562" alt="image" src="https://user-images.githubusercontent.com/513813/165687974-3705858b-3f01-435b-954a-3de55012619f.png">

The problem is that the Desktop DB is not being populated, so the Finder doesn't know that StuffIt Expander is associated with `SIT!`/`SITx`, which is being tracked in issue #4. Once you open the app once (or even go its folder) the Finder updates the association and double-clicking should work.

**Comment by mihaip** [comment]
Desktop DB is now being generated, and double-clicking on .sit files should work now.
