### ISSUE TITLE
import-basilisk-ii fails because of missing files

### ISSUE THREAD

**Issue by geocolumbus** [mihaip/infinite-mac#65]
On an M1 MacBook Air, this command:

`npm run import-basilisk-ii`

results in
```
> infinite-mac@0.1.0 import-basilisk-ii
> scripts/import-basilisk-ii.sh

cp: scripts/../macemu/BasiliskII/src/Unix/BasiliskII: No such file or directory
cp: scripts/../macemu/BasiliskII/src/Unix/BasiliskII.wasm: No such file or directory
Traceback (most recent call last):
  File "/Users/georgecampbell/Emulators/infinite-mac/scripts/rewrite-basilisk-ii-source-map.py", line 10, in <module>
    with open(input_path, "r") as input_file:
FileNotFoundError: [Errno 2] No such file or directory: 'scripts/../macemu/BasiliskII/src/Unix/BasiliskII.wasm.map'
```
An inspection of `https://github.com/mihaip/macemu` shows that no such file exists in the repository.

**Comment by mihaip** [comment]
This requires that the Basilisk II binary be recompiled, see https://github.com/mihaip/infinite-mac#building-basilisk-ii for details. This is only needed if making changes to Basilisk itself, otherwise you can use the binary that's in this repo.

Will make the script fail more gracefully in this case.
