### ISSUE TITLE
screenshot shortcut is not caught

### ISSUE THREAD

**Issue by eduo** [mihaip/infinite-mac#69]
I assume this is because MacOS "captures" the keys themselves, but is there a way to execute the  screenshot shortcuts within the emulation and have System 7 save the captured file "normally" in its desktop?

**Comment by mihaip** [comment]
I'm guessing that macOS (the modern version) always intercepts Command-Shift-3, and there's no way for the browser (or a web page within it) to get it. The most likely workaround is to allow control to be mapped to command (see #10), so that Control-Shift-3 could be used instead. I will be looking into that at some point, you subscribe to that issue to get updates.

**Comment by eduo** [comment]
Thank you. I was suspecting the shortcut it caught at a much lower level than anything available in a browser. Will subscribe to the other one.

**Comment by eduo** [comment]
Silly me. This has been implemented already. Works for me in macos8 but not in system7, weirdly. Other combinations do work.

Thanks!

**Comment by mihaip** [comment]
It works in System 7 too for me:

<img width="987" alt="image" src="https://user-images.githubusercontent.com/513813/194770720-40e2a29d-9e5e-444e-aaad-d81c70e81044.png">

**Comment by eduo** [comment]
How strange. I tried in Edge for mac on full screen. Will try with other browsers and platforms and try to find a pattern.

**Comment by eduo** [comment]
I think you may have commented on the wrong ticket. This is the github for infinitemac and the ticket is about mapping special keys.
