### ISSUE TITLE
Investigate mini vMac

### ISSUE THREAD

**Issue by mihaip** [mihaip/infinite-mac#71]
It would allow System 6 (or older?) to run. https://github.com/yksoft1/minivmac-em is an Emscripten port (https://github.com/leonier/minivmac-em is a fork that is updated with the current mini vMac release).

mini vMac itself it in a bit of a weird state, the author [has not been heard from recently](https://www.emaculation.com/forum/viewtopic.php?t=11570). https://github.com/minivmac/minivmac is an unofficial GitHub mirror.

- [x] Wasm build system
- [x] Video
- [x] Input
- [x] Idlewait 
- [x] Stop reallocating the browser framebuffer every time
- [x] Take into account dirty rect when blitting
- [x] Lookup table for 1-bit -> 32-bit expansion
- [x] Re-evaluate System 6 image (something with MultiFinder enabled?)
- [x] Import useful [extras](https://www.gryphel.com/c/minivmac/extras/index.html) into Infinite HD
- [x] Fix Infinite HD getting read at startup (due to a desktop rebuild?)
- [x] Alternative to Stickies with instructions (Read Me file opened by TeachText?)
- [x] Delay first idlewait until disks are actually mounted
- [x] Respecting of dynamic idlewait value
- [x] Pre-size monitor to fixed size on JS size, instead of waiting for video system to be initialized
- [x] Register and serve from system6.app
- [x] Move welcome doc to desktop and don't auto-open it
- [x] Disk image mounting
- [x] Fix keyboard arrow keys not being recognized
- [x] Mac II/color support
- [x] Re-mount disks when restarting
- [x] "Welcome" doc positioning when running in 640x480
- [x] Re-evaluate default speed multiplier (8x? maximum?)
- [x] Audio
- [ ] 128K and other models
- [ ] Mac II variants that support 16, thousands and millions of colors
- [ ] #147
- [ ] Can we use the custom icon for Infinite HD?
- [ ] #148
- [ ] #149
- [ ] #150
- [ ] #151
- [ ] #152

**Comment by mihaip** [comment]
First light:
<img width="744" alt="image" src="https://user-images.githubusercontent.com/513813/211244838-43e649ae-5d0c-4bd4-b07a-72b34fcb8691.png">

(I'm doing my own Emscripten port instead of relying on the existing one because I don't want to go through the SDL compatibility layer)

**Comment by that-ben** [comment]
Regarding the speed multiplier, please note that some very old titles from 1984 to 1986 will NOT be playable at any speed except 1X so there has to be a way to keep the 1X option available, albeit probably not the default speed.  IMHO, 4X is a decent default speed for Mini vMac and 16X is nice for Mini vMac II.  Starting from System 6, about 99% of the games already used proper timer objects so that no matter what speed multiplier you used, it would not make it unplayable.  But before System 6, the more you go back, the more they require 1X.

**Comment by mihaip** [comment]
Yeah, I'll most likely have a 128K (or 512K for the extra headroom?) build. I already have separate Mac Plus and Mac II builds so I could try out color support (latter is not currently exposed under a separate domain, but you can see it at https://system6.app/?domain=system6-ii.app)

**Comment by that-ben** [comment]
> can see it at https://system6.app/?domain=system6-ii.app)

:+1:  Yes and it boots crazy fast too, like almost instantaneous! Though, is it normal at this stage that it only offers B&W and 256 (8-bit) colors modes? I feel like Mac II builds should also offer the 16 colors (4-bit) mode as there are (rare, but some) titles that require the 16 colors mode and they don't launch on anything else (while some will fall back on B&W mode).  An example of a game that only runs in 16 colors mode and nothing else (and note that I'm not judging how good or bad a software title is here) would be MyDude: https://www.macintoshrepository.org/files/direct/9421_MyDude.dsk

The whole reason I stumbled upon your project last year was because you were the absolute first one to compile and publish a WASM Mac emulator that supported 16 colors (4-bit) mode.  I have spent hours upon hours in trying to find one and at the time you were the very first one to have managed that, so I feel like this extremely abandoned/forgotten color mode should be included in the Mac II build.

**Comment by mihaip** [comment]
Color support is a built-time option in Mini vMac: https://www.gryphel.com/c/minivmac/options.html#option_depth. You can only specify one color depth that's supported (in addition to black and white). 

It might be possible to support multiple options simultaneously, but it would require modifications to Mini vMac itself, which I'm trying to minimize.

**Comment by that-ben** [comment]
In that case, then can we have both 16 and 256 colors mode builds separately available through the GET[domain] parameter or something like that?

Also, I can't help but to ask myself how your Infinite HD partition will work under System 1.0 or even 2.0, back when Mac OS only supported MFS and not HFS.  Plus, even if it were made into a MFS partition, it can only support up to 20MB, while your Infinite HD disk image is over 900MB... Does it even make sense to mount the current Infinite HD partition on a B&W emulated Mac environment? Most of what's in it cannot even run in pre-System 6 to begin with.  I would think we could perhaps have a B&W only Infinite HD, something like "Infinite FD" for 1980's Mac environments.

**Comment by Iritscen** [comment]
Really happy to see Mini vMac being made accessible like this!  As mentioned, most of the third-party software on the Infinite HD won't run in a Sys6/B&W environment so hopefully at some point you can assemble a different disk image with a more compatible library of apps.  Good sources of old software include Mini vMac's [Extras](https://www.gryphel.com/c/minivmac/extras/index.html) and [Software](https://www.gryphel.com/c/sw/index.html) pages.

Also, I would really like to see 1X speed offered for the sake of authenticity.  Even an app from 1990 – Gnop!, the first game from "Bungie" (Alex Seropian) – has an animation (the paddle death) which is apparently tied to clock speed; it runs so fast you can't really see it unless MvM's speed is turned down.  System speed is a runtime option in MvM so hopefully that's not too hard to add, perhaps in the Settings next to the Apple logo.

**Comment by mihaip** [comment]
There is now a speed option in the settings dialog, allowing 1x (or All Out) to be selected:
<img width="725" alt="image" src="https://user-images.githubusercontent.com/513813/220038987-1437fc62-e230-4e9e-9738-96f900b1030e.png">

**Comment by mihaip** [comment]
As for using MFS, I agree that it'll be necessary once older versions of the OS are available. Ideally I'd still like to generate the disk image programmatically, though thus far I have not found any MFS libraries that support writing new volumes (e.g. https://github.com/barberd/macmfsextract and https://github.com/st3fan/mfs are for reading only). https://github.com/leiless/MFSLives is the closest, though it's done as a VFS plug-in.

**Comment by Iritscen** [comment]
Love the speed setting!  Even with the misspelled "software" ;-)

**Comment by mihaip** [comment]
> Love the speed setting! Even with the misspelled "software" ;-)

Oops, should be fixed.

**Comment by mihaip** [comment]
Declaring this done I've filed other GitHub issues for the lingering tasks (#147, #148, #149, #150, #151, #152).
