### ISSUE TITLE
Strange audio behavior (lag + random audio chunk order?)

### ISSUE THREAD

**Issue by that-ben** [mihaip/infinite-mac#85]
Audio in macos9.app is laggy.  This is expected since it's emulated, but it's exhibiting a strange behavior:

1) If you play audio and stop it while it's playing (e.g. by pressing the STOP button in SoundApp) then whatever audio chunk was currently playing will be kept in memory and will play back once you start playing another sound.  For instance, if you play back a music track, then stop it, then play back an entirely different music track, half a second of audio from the previous audio track will be heard at the beginning of the second track.

2) The JS console will always say that audio callback has starved sending audio by the exact time that elapsed between the moment that you stopped playing a sound and the moment that you started playing another one.  (e.g. if you play back a music and hit PAUSE for 3 seconds then hit PLAY, the JS console will say that audio callback has starved sending audio by 3 seconds.)

3) Audio chunks often play in a seemingly random order, like instead of chunks 1,2,3,4 you will hear chunks 2,1,4,3, much like if there was a race condition when playing audio chunks.

See the following MP4 video that shows those behaviors: https://www.macintoshrepository.org/files/direct/macos9app_20221227-094510.mp4

**Comment by mihaip** [comment]
I understand the audio code the least well (out of all the Basilisk II/SheepShaver subsystems). https://github.com/mihaip/macemu/commit/611d48c3f76ec20020aee66c652119d296fbe9dd is a change that I made to make the playback less laggy, but it it have the effect of the same sample being played back more than once.

There is also this comment from James's original Emscripten port, I don't yet understand the implications of the changing that timing cadence: https://github.com/mihaip/macemu/blob/82446d09ae45f46889161f4dabefd57753216700/BasiliskII/src/Unix/main_unix.cpp#L1295-L1298

One thing to look into is to replace the entire JS side of the audio handling with an [AudioWorklet](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Using_AudioWorklet), which may allow the entire thing to be less timing sensitive (instead of the web and Basilisk II/Mac side having to run two loops in parallel, the emulator can drive the audio worklet itself).

**Comment by mihaip** [comment]
Things should be better with the switch to an audio worklet -- I'm able to play back songs using SoundApp reliably.

**Comment by that-ben** [comment]
Uhm... Things are DIFFERENT, which I guess could partially fit Apple's slogan! 🤣 ... but audio in SheepShaver.js is still very weird here.  I don't know why, but I see it play WAY TOO FAST 🏃‍♂️ under certain circumstances, compared to regular SheepShaver for Windows?!

Here's a video to demonstrate the issue: https://www.macintoshrepository.org/files/direct/macos9app_20230210-091227.mp4

- First half of the video is under regular SheepShaver.exe v2.5 in Windows.
- Second half of the video is in https://macos9.app
- The disk image for the tracker modules can directly be downloaded here: https://www.macintoshrepository.org/files/direct/Trackers-Electro2.iso

**Comment by mihaip** [comment]
Interesting. I'm not able to reproduce this. What browser and OS are you trying it on? If you open https://macos9.app/?debug_audio=true and show the console, what kind of output do you see? This is what I get when playing (it's normal for the buffer to be somewhat full, but it should not be at 0% because then silence will be generated, or audio will be skipped if at 100%)
<img width="1912" alt="image" src="https://user-images.githubusercontent.com/513813/218273463-a129e7ba-fd49-4bc8-970f-e2e95c107044.png">

**Comment by that-ben** [comment]
Thanks for reopening this thread.

As usual, I'm under Windows 7 (64-bit) w/ Firefox (most recent, which is as of posting this v109.0)

I have been trying for well over 10 minutes now.  I cannot get any different disk image to mount in the app on that link https://macos9.app/?debug_audio=true

All it gives me is the same old disk image from a couple days ago.  Even though I made a new disk image with different files in it, I renamed the file to something else, etc... I cannot mount any new disk image.  Is there a way to flush the disk image cache in your app?

**Comment by mihaip** [comment]
I'm still not able to reproduce the behavior you're seeing (I don't have access to a Windows machine, I tried Firefox 109 on a Mac).

It's possible that this is machine speed dependent. How quickly does the emulator come up for you? There are some timers output to the console when it's first launched. I see:

Emulator first blit: 612.16ms (this is the first time the screen is drawn to)
Emulator quiescent: 13853.74ms (this is how long it takes to get to the desktop/Finder)

**Comment by that-ben** [comment]
I have kind of a slow internet (30mbps shared with 4 people) but...
My emulator first blit is: Emulator first blit: 1540.26ms
My emulator quiescent is: 31624.32ms

Is that bad?

I have a request regarding this issue: Could you add a couple .mod, .it and .s3m trackers in your public Mac OS 9 disk image so that I can test it on an iPad tomorrow? You could take random trackers from this disk image if you want: https://www.macintoshrepository.org/files/direct/30-trackers.dsk

I guess adding a couple music tracker files could count in exchange for the donation I made a couple days ago on your Paypal.  It said on your sponsorship page that we could ask for files to be added lol ;-)

**Comment by mihaip** [comment]
That's a great observation. I had been testing by dragging in `.mod` files directly, which does not cause the emulator be restarted. I had missed a place where we need to stop the existing audio context when doing a restart.

**Comment by mihaip** [comment]
Fix is deployed if you want to try again

(happy to add the tracker files too the next time I rebuild the Infinite HD disk image -- it takes a while to re-upload all of it so I batch it up with other software changes)

**Comment by that-ben** [comment]
OH WOW, that fixed it! Congratulations on fixing this bug! 🥳
